package com.example.jetpackcomposetutorial.StartupFunctions

import com.example.jetpackcomposetutorial.BabyTask
import com.example.jetpackcomposetutorial.listOfEveryTask

fun ResetAllAppTasks(){


    for (i in 1..36){
        listOfEveryTask.add(BabyTask(i, "[		]","				"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Shelving	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	(Sliding doors)	: 	guide installed	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Door	: 	(hinges/screws)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Door	: 	(not ghosting)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far closet	]","	Door	: 	(door stop, strike)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Toilet	: 	working, bolt caps	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Tp/towel holder	: 	level, anchored	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Vanity light	: 	level, cracks, bulbs	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Mirror	: 	level, damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Sink	: 	hot water, stopper	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Vanity top	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Vanity cabinet	: 	major damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Tub/shower	: 	(door opens easily)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Tub/shower	: 	(curtain rod)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Tub/shower	: 	hardware, water works	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Tub/shower	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Fan	: 	level, not loud	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Door	: 	hinges/screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Door	: 	not ghosting	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bathroom	]","	Door	: 	door stop, strike	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Windows	: 	cracks, screens	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Windows	: 	hardware, opens, lockable	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Blinds	: 	valance, working	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Light	: 	cracks, bulbs	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Door	: 	hinges/screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Door	: 	not ghosting	"	))
        listOfEveryTask.add(BabyTask(i, "[	Far bedroom	]","	Door	: 	door stop, strike	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Windows	: 	cracks, screens	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Windows	: 	hardware, opens, lockable	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Blinds	: 	valance, working	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	(Glass sliding doors)	: 	cracks, screens, lockable	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	Thermostat	: 	working	"	))
        listOfEveryTask.add(BabyTask(i, "[	Living room	]","	(Plumbing cleanouts)	: 	installed	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Floor	: 	lvt gaps, buckling	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Backsplash	: 	cracks, missing grout	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Island lights	: 	cracks, bulbs	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Dining lights	: 	bulbs	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Counter tops	: 	damages, siliconed on	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Sink	: 	both waters	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Sink	: 	hose goes back up	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Disposal	: 	working	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Dishwasher	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Dishwasher	: 	no leaks/errors	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Microwave	: 	damages, working	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Oven	: 	damages, scratches	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Oven	: 	plugged in, pushed back	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Fridge	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Fridge	: 	water/ice works	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Cabinets	: 	major damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Cabinets	: 	shelves, door swings	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Pantry	: 	shelves, floor/ceiling	"	))
        listOfEveryTask.add(BabyTask(i, "[	Kitchen	]","	Pantry	: 	door	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Ceiling	: 	(vents, lights, sprinklers)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Floor	: 	lvt gaps, buckling	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Shelving	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Washer	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Washer	: 	leaks/errors	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Dryer	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Dryer	: 	heat works	"	))
        listOfEveryTask.add(BabyTask(i, "[	Laundry room	]","	Door(s)	: 	(Strike(s), ball catches)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Electric panel	]","	Breakers	: 	on	"	))
        listOfEveryTask.add(BabyTask(i, "[	Electric panel	]","	Latch	: 	not stuck closed	"	))
        listOfEveryTask.add(BabyTask(i, "[	Electric panel	]","	Screws	: 	installed	"	))
        listOfEveryTask.add(BabyTask(i, "[	Patio/balcony	]","	Light	: 	bulb	"	))
        listOfEveryTask.add(BabyTask(i, "[	Patio/balcony	]","	Siding	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Furnace room	]","	Furnace	: 	Filter clean	"	))
        listOfEveryTask.add(BabyTask(i, "[	Furnace room	]","	Furnace	: 	Not frozen or leaking	"	))
        listOfEveryTask.add(BabyTask(i, "[	Furnace room	]","	Door	: 	hinges/screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Furnace room	]","	Door	: 	not ghosting	"	))
        listOfEveryTask.add(BabyTask(i, "[	Furnace room	]","	Door	: 	door stop, strike	"	))
        listOfEveryTask.add(BabyTask(i, "[	Hallway	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Hallway	]","	Floor	: 	lvt gaps, buckling	"	))
        listOfEveryTask.add(BabyTask(i, "[	Hallway	]","	Entry door	: 	door viewer	"	))
        listOfEveryTask.add(BabyTask(i, "[	Hallway	]","	Entry door	: 	no threshold gap	"	))
        listOfEveryTask.add(BabyTask(i, "[	Hallway	]","	Entry door	: 	weatherstrip	"	))
        listOfEveryTask.add(BabyTask(i, "[		]","	(ALL ARE N/A BELOW FOR 1 BED UNITS)	: 		"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Shelving	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	(Sliding doors)	: 	guide installed	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Door	: 	(hinges/screws)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Door	: 	(not ghosting)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bed closet	]","	Door	: 	(door stop, strike)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Toilet	: 	working, bolt caps	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Tp/towel holder	: 	level, anchored	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Vanity light	: 	level, cracks, bulbs	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Mirror	: 	level, damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Sink	: 	hot water, stopper	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Vanity top	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Vanity cabinet	: 	major damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Tub/shower	: 	(door opens easily)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Tub/shower	: 	(curtain rod)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Tub/shower	: 	hardware, water works	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Tub/shower	: 	damages	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Fan	: 	level, not loud	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Door	: 	hinges/screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Door	: 	not ghosting	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bathroom	]","	Door	: 	door stop, strike	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Ceiling	: 	vents, lights, sprinklers	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Floor	: 	(lvt gaps/buckling)	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Outlets/switches	: 	level, screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Windows	: 	cracks, screens	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Windows	: 	hardware, opens, lockable	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Blinds	: 	valance, working	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Light	: 	cracks, bulbs	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Door	: 	hinges/screws	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Door	: 	not ghosting	"	))
        listOfEveryTask.add(BabyTask(i, "[	Close bedroom	]","	Door	: 	door stop, strike	"	))


        //add farBedClosetTasks()
            //addCeilingTasks()
                //add ceiling task
                //add sprinkler heads task
            //addDoorTasks()
                //add door closes task
                //add
            //add shelves task
            //add outlets task

    }

}

